spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/employee_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    com.example.employeemanagement: INFO
